version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: w2y_auth_development
    volumes:
      - w2y_auth_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: w2y_auth_development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    stdin_open: true
    tty: true

volumes:
  w2y_auth_db_data:
